# Generated by Django 6.0 on 2025-12-15 04:33

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_admin_wallet', models.BooleanField(default=False, verbose_name='Админский кошелёк')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Кошелёк',
                'verbose_name_plural': 'Кошельки',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Комиссия')),
                ('idempotency_key', models.CharField(editable=False, max_length=255, verbose_name='Ключ')),
                ('from_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_wallets', to='transactions.wallet', verbose_name='Списано с кошелька')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_wallets', to='transactions.wallet', verbose_name='Зачислено на кошелёк')),
            ],
            options={
                'verbose_name': 'Перевод',
                'verbose_name_plural': 'Переводы',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('flow', models.CharField(choices=[('debit', 'Начисление'), ('credit', 'Списание'), ('fee', 'Комиссия')], verbose_name='Движение')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.transfer', verbose_name='Перевод')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.wallet', verbose_name='Кошелёк')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
        migrations.CreateModel(
            name='WalletBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Баланс')),
                ('version', models.PositiveIntegerField(default=0, editable=False, verbose_name='Версия')),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='transactions.wallet', verbose_name='Кошелёк')),
            ],
            options={
                'verbose_name': 'Баланс кошелька',
                'verbose_name_plural': 'Баланс кошельков',
            },
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(condition=models.Q(('is_admin_wallet', True)), fields=('is_admin_wallet',), name='unique_admin_wallet'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.UniqueConstraint(fields=('from_wallet', 'idempotency_key'), name='unique_transfer'),
        ),
    ]
